# coding: utf-8

"""
    Kill Bill

    Kill Bill is an open-source billing and payments platform

    The version of the OpenAPI document: 0.24.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from openapi_client.models.unit_usage_record import UnitUsageRecord
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SubscriptionUsageRecord(BaseModel):
    """
    SubscriptionUsageRecord
    """ # noqa: E501
    subscription_id: StrictStr = Field(alias="subscriptionId")
    tracking_id: Optional[StrictStr] = Field(default=None, alias="trackingId")
    unit_usage_records: List[UnitUsageRecord] = Field(alias="unitUsageRecords")
    __properties: ClassVar[List[str]] = ["subscriptionId", "trackingId", "unitUsageRecords"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SubscriptionUsageRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in unit_usage_records (list)
        _items = []
        if self.unit_usage_records:
            for _item in self.unit_usage_records:
                if _item:
                    _items.append(_item.to_dict())
            _dict['unitUsageRecords'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SubscriptionUsageRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "subscriptionId": obj.get("subscriptionId"),
            "trackingId": obj.get("trackingId"),
            "unitUsageRecords": [UnitUsageRecord.from_dict(_item) for _item in obj.get("unitUsageRecords")] if obj.get("unitUsageRecords") is not None else None
        })
        return _obj


