# coding: utf-8

"""
    Kill Bill

    Kill Bill is an open-source billing and payments platform

    The version of the OpenAPI document: 0.24.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr, field_validator
from pydantic import Field
from openapi_client.models.tier_price import TierPrice
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UsagePrice(BaseModel):
    """
    UsagePrice
    """ # noqa: E501
    usage_name: Optional[StrictStr] = Field(default=None, alias="usageName")
    usage_type: Optional[StrictStr] = Field(default=None, alias="usageType")
    billing_mode: Optional[StrictStr] = Field(default=None, alias="billingMode")
    tier_block_policy: Optional[StrictStr] = Field(default=None, alias="tierBlockPolicy")
    tier_prices: Optional[List[TierPrice]] = Field(default=None, alias="tierPrices")
    __properties: ClassVar[List[str]] = ["usageName", "usageType", "billingMode", "tierBlockPolicy", "tierPrices"]

    @field_validator('usage_type')
    def usage_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('CAPACITY', 'CONSUMABLE'):
            raise ValueError("must be one of enum values ('CAPACITY', 'CONSUMABLE')")
        return value

    @field_validator('billing_mode')
    def billing_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('IN_ADVANCE', 'IN_ARREAR'):
            raise ValueError("must be one of enum values ('IN_ADVANCE', 'IN_ARREAR')")
        return value

    @field_validator('tier_block_policy')
    def tier_block_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('ALL_TIERS', 'TOP_TIER'):
            raise ValueError("must be one of enum values ('ALL_TIERS', 'TOP_TIER')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UsagePrice from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tier_prices (list)
        _items = []
        if self.tier_prices:
            for _item in self.tier_prices:
                if _item:
                    _items.append(_item.to_dict())
            _dict['tierPrices'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UsagePrice from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "usageName": obj.get("usageName"),
            "usageType": obj.get("usageType"),
            "billingMode": obj.get("billingMode"),
            "tierBlockPolicy": obj.get("tierBlockPolicy"),
            "tierPrices": [TierPrice.from_dict(_item) for _item in obj.get("tierPrices")] if obj.get("tierPrices") is not None else None
        })
        return _obj


